# Generated by Django 5.1.5 on 2025-02-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="puzzle_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple Choice Question"),
                    ("code", "Coding Challenge"),
                ],
                default="mcq",
                max_length=4,
            ),
        ),
    ]
