# Generated by Django 5.1.5 on 2025-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle", "0002_puzzle_puzzle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="expected_output",
            field=models.TextField(
                blank=True, help_text="Expected output for coding puzzles", null=True
            ),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="starter_code",
            field=models.TextField(
                blank=True,
                help_text="Initial code template for coding puzzles",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="feedback",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
